_core:
  default_config_hash: 4GIX5Esnc_umpXUBj4IIocRX7Mt5fPhm4AgXfE3E56E
module:
  admin_toolbar: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  anct_settings: 0
  announcements_feed: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor5: 0
  ckeditor5_plugin_pack: 0
  ckeditor5_plugin_pack_templates: 0
  comment: 0
  config: 0
  contact: 0
  contextual: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  gin_login: 0
  gin_toolbar: 0
  help: 0
  history: 0
  image: 0
  inline_form_errors: 0
  language: 0
  layout_builder: 0
  layout_discovery: 0
  layout_options: 0
  layout_paragraphs: 0
  link: 0
  locale: 0
  media: 0
  media_library: 0
  menu_link_content: 0
  menu_ui: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  search: 0
  shortcut: 0
  single_content_sync: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  twig_tweak: 0
  ui_patterns: 0
  ui_patterns_ds: 0
  ui_patterns_field_group: 0
  ui_patterns_layouts: 0
  ui_patterns_library: 0
  ui_patterns_settings: 0
  ui_patterns_views: 0
  ui_styles: 0
  ui_styles_block: 0
  ui_styles_ckeditor5: 0
  ui_styles_library: 0
  ui_styles_views: 0
  update: 0
  user: 0
  views_ui: 0
  ds: 1
  views: 10
  paragraphs: 11
  minimal: 1000
theme:
  olivero: 0
  claro: 0
  gin: 0
  ui_suite_dsfr: 0
  anct: 0
profile: minimal
